services:
  jupyter:
    build:
      context: .
      args:
        - UID=${UID}
        - GID=${GID}
    restart: unless-stopped
    volumes:
      - ./notebooks/:/home/host/notebooks/
    ports:
      - 8808:8888
